rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby
  - jruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx

before_install:
  - gem update --system 2.4.8
  - gem --version

branches:
  except:
    - artoo.io

notifications:
  irc: "irc.freenode.org#artoo"
